name: Frontend Web
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-react-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run dev

  Coding-Style:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: |
          npx eslint ./src ./vite.config.js ./eslint.config.ts \
            --ext .js,.jsx,.ts,.tsx \
            --max-warnings=0